title: CommonerLLP
description: CommonerLLP public website.
url: "https://commonerllp.org"
theme: minima
github_username: CommonerLLP
header_pages:
  - index.md

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
